[phases.setup]
nixPkgs = ["python3"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run db:migrate && pnpm run build"]

[start]
cmd = "pnpm run db:migrate && npx next start -p ${PORT:-3002}"
